/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;

/**
 *
 * @author Alumno
 */
public class ventanaInsertar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaInsertar.class.getName());

    /**
     * Creates new form ventanaInsertar
     */
    public ventanaInsertar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        botonEjercicio = new javax.swing.JButton();
        botonRutina = new javax.swing.JButton();
        botonUsuario = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiTitulo.setText("¿Que desea Insertar?");

        botonEjercicio.setText("Ejercicio");
        botonEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjercicioActionPerformed(evt);
            }
        });

        botonRutina.setText("Rutina");
        botonRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRutinaActionPerformed(evt);
            }
        });

        botonUsuario.setText("Usuario");
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTitulo)
                .addGap(39, 39, 39)
                .addComponent(botonEjercicio)
                .addGap(18, 18, 18)
                .addComponent(botonRutina)
                .addGap(18, 18, 18)
                .addComponent(botonUsuario)
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjercicioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ventanaInsertarEjercicio(ge, gr).setVisible(true);
    }//GEN-LAST:event_botonEjercicioActionPerformed

    private void botonRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRutinaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ventanaInsertarRutina(gr, gu).setVisible(true);
    }//GEN-LAST:event_botonRutinaActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ventanaInsertarUsuario(gu).setVisible(true);
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void volver() {
    this.dispose(); // cierra solo esta ventana
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEjercicio;
    private javax.swing.JButton botonRutina;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
