/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import gestores.GestorBD;
import gestores.GestorEjercicios;
import gestores.GestorFicheros;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class ventanaExportar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    GestorFicheros gf;
    GestorBD gbd;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaExportar.class.getName());

    /**
     * Creates new form ventanaImportar
     */
    public ventanaExportar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge,GestorFicheros gf, GestorBD gbd) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        this.gf = gf;
        this.gbd = gbd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        etiExportar = new javax.swing.JLabel();
        botonTexto = new javax.swing.JButton();
        botonBinario = new javax.swing.JButton();
        botonDom = new javax.swing.JButton();
        botonJAXB = new javax.swing.JButton();
        botonSQLite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        etiExportar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiExportar.setText("Exportar");

        botonTexto.setText("Texto");
        botonTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTextoActionPerformed(evt);
            }
        });

        botonBinario.setText("Binario");
        botonBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBinarioActionPerformed(evt);
            }
        });

        botonDom.setText("DOM");
        botonDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDomActionPerformed(evt);
            }
        });

        botonJAXB.setText("JAXB");
        botonJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJAXBActionPerformed(evt);
            }
        });

        botonSQLite.setText("SQLite");
        botonSQLite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSQLiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(etiExportar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(botonVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiExportar)
                .addGap(18, 18, 18)
                .addComponent(botonTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTextoActionPerformed
        // TODO add your handling code here:
        try {
            GestorFicheros.exportarTodoTexto(gu, gr, ge);
            JOptionPane.showMessageDialog(this, 
                "Datos exportados correctamente a los archivos:\n" +
                "usuarios.txt\nrutinas.txt\nejercicios.txt", 
                "Exportación completada", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al exportar los datos: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonTextoActionPerformed

    private void botonBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBinarioActionPerformed
        // TODO add your handling code here:
        try {
            GestorFicheros.exportarBinario(
                gu.getUsuarios(),
                gr.getRutinas(),
                ge.getEjercicios()
                );
            JOptionPane.showMessageDialog(this, "Datos exportados correctamente en formato binario.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al exportar los datos: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBinarioActionPerformed

    private void botonDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDomActionPerformed
        // TODO add your handling code here:
        // Crear instancia de GestorFicheros
        GestorFicheros gestor = new GestorFicheros();

        // Llamar al método que exporta todo a XML
        gestor.exportarTodoXML(gu, gr, ge);

        // Mensaje opcional para el usuario
        JOptionPane.showMessageDialog(this, "Datos exportados correctamente a XML (DOM).");
    }//GEN-LAST:event_botonDomActionPerformed

    private void botonJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJAXBActionPerformed
        // TODO add your handling code here:
        GestorFicheros gf = new GestorFicheros();
        gf.exportarJAXB(gu.getUsuarios(), gr.getRutinas(), ge.getEjercicios());
    }//GEN-LAST:event_botonJAXBActionPerformed

    private void botonSQLiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSQLiteActionPerformed
        // TODO add your handling code here:
        if (gbd == null) {
            gbd = new GestorBD();
        }
        gbd.exportarTodo(gu, gr, ge);
    }//GEN-LAST:event_botonSQLiteActionPerformed

    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBinario;
    private javax.swing.JButton botonDom;
    private javax.swing.JButton botonJAXB;
    private javax.swing.JButton botonSQLite;
    private javax.swing.JButton botonTexto;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiExportar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
