/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Alumno
 */
public class ventanaModificar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaModificar.class.getName());

    /**
     * Creates new form ventanaModificar
     */
    public ventanaModificar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonModUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonModUsuarios.setText("Modificar Usuarios");
        botonModUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModUsuariosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Modificar");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(botonModUsuarios)
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(botonVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(botonModUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            String idStr = JOptionPane.showInputDialog(this, "Introduce el ID del usuario a modificar:");
            if (idStr == null || idStr.trim().isEmpty()) return;

            int id = Integer.parseInt(idStr);
            Usuario u = gu.buscarPorId(id);

            if (u != null) {
                String nuevoNombre = JOptionPane.showInputDialog(this, "Nuevo nombre:", u.getNombre());
                String edadStr = JOptionPane.showInputDialog(this, "Nueva edad:", u.getEdad());
                String pesoStr = JOptionPane.showInputDialog(this, "Nuevo peso:", u.getPeso());
                String alturaStr = JOptionPane.showInputDialog(this, "Nueva altura:", u.getAltura());

                if (nuevoNombre != null && edadStr != null && pesoStr != null && alturaStr != null) {
                    gu.modificarUsuario(id, nuevoNombre, Integer.parseInt(edadStr), 
                            Double.parseDouble(pesoStr), Double.parseDouble(alturaStr));
                    JOptionPane.showMessageDialog(this, "Usuario modificado correctamente.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un usuario con ese ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar usuario: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModUsuariosActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModUsuarios;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
