/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import excepciones.MyException;
import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import modelo.Usuario;

/**
 *
 * @author Alumno
 */
public class ventanaInsertarRutina extends javax.swing.JFrame {
    GestorRutinas gr;
    GestorUsuarios gu;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaInsertarRutina.class.getName());

    /**
     * Creates new form ventanaInsertarRutina
     */
    public ventanaInsertarRutina(GestorRutinas gr, GestorUsuarios gu) {
        this.gr = gr;
        this.gu = gu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        etiTitulo1 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        etiNombre = new javax.swing.JLabel();
        etiIdUsu = new javax.swing.JLabel();
        fieldIdUsu = new javax.swing.JTextField();
        botonInsertar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiTitulo1.setText("Insertar Rutina");

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        etiNombre.setText("Nombre");

        etiIdUsu.setText("Id de usuario que usara la rutina");

        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(etiTitulo1))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(botonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiIdUsu)
                            .addComponent(fieldIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiNombre)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTitulo1)
                .addGap(54, 54, 54)
                .addComponent(etiNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiIdUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInsertar)
                    .addComponent(botonVolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        // TODO add your handling code here:
        try {
            // 1.  Comprobar campos no estan vacios y Recoger datos de los campos
            comprobarCampos();
            String nombre = fieldNombre.getText();
            int idUsu = Integer.parseInt(fieldIdUsu.getText());
            // 2. Insertar con el gestor
                   gr.insertar(nombre, idUsu);
            // 3. Mostrar confirmación
            JOptionPane.showMessageDialog(this, "Rutina insertada correctamente", "Exito", INFORMATION_MESSAGE);
            // 4. Limpiar campos
            fieldNombre.setText("");
            fieldIdUsu.setText("");
            System.out.println("Total rutinas registradas: " + gr.getRutinas().size());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error, asegurese de poner bien los datos", "Error", ERROR_MESSAGE);
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar rutina: " + ex.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void comprobarCampos() {
        if (fieldNombre.getText().isEmpty() || fieldIdUsu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", ERROR_MESSAGE);
            return;
        }
    }
    
    private void volver() {
    this.dispose(); // cierra solo esta ventana
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiIdUsu;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiTitulo1;
    private javax.swing.JTextField fieldIdUsu;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
