/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import excepciones.MyException;
import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import modelo.Ejercicio;
import modelo.Usuario;

/**
 *
 * @author Alumno
 */
public class ventanaBorrar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaBorrar.class.getName());

    /**
     * Creates new form ventanaBuscar
     */
    public ventanaBorrar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBorrarUsuarioPorID = new javax.swing.JButton();
        botonBorrarRutina = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonBorrarRutina1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Borrador");

        botonBorrarUsuarioPorID.setText("Borrar Usuario");
        botonBorrarUsuarioPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarUsuarioPorIDActionPerformed(evt);
            }
        });

        botonBorrarRutina.setText("Borrar Rutina");
        botonBorrarRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarRutinaActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonBorrarRutina1.setText("Borrar Ejercicio");
        botonBorrarRutina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarRutina1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBorrarUsuarioPorID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrarRutina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrarRutina1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonVolver)
                                .addGap(50, 50, 50)))
                        .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(botonBorrarUsuarioPorID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrarRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrarRutina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarUsuarioPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarUsuarioPorIDActionPerformed
        // TODO add your handling code here:
            try {
                String input = JOptionPane.showInputDialog(this, "Introduzca el ID del usuario a borrar:");
                if (input == null) {
                    // Usuario pulsó Cancelar
                    return;
                }
                input = input.trim();
                if (input.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe introducir un ID válido.", "Error", ERROR_MESSAGE);
                    return;
                }

                int id = Integer.parseInt(input);

                // Confirmar antes de borrar
                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de que desea borrar el usuario con ID " + id + "?",
                        "Confirmar borrado",
                        JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    Usuario u = gu.buscarPorId(id); // opcional si quieres mostrar nombre antes de borrar
                    if (u != null) {
                        gu.borrar(id);
                        JOptionPane.showMessageDialog(this, "Usuario borrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró ningún usuario con ese ID.", "Error", ERROR_MESSAGE);
                    }
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error", ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al borrar usuario: " + ex.getMessage(), "Error", ERROR_MESSAGE);
            }
    }//GEN-LAST:event_botonBorrarUsuarioPorIDActionPerformed

    private void botonBorrarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarRutinaActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog(this, "Introduzca el ID de la rutina a borrar:");
            if (input == null) return; // cancelar
            input = input.trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe introducir un ID válido.", "Error", ERROR_MESSAGE);
                return;
            }

            int id = Integer.parseInt(input);
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea borrar la rutina con ID " + id + "?",
                    "Confirmar borrado",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (gr.buscarPorId(id) != null) {
                    gr.borrar(id);
                    JOptionPane.showMessageDialog(this, "Rutina borrada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ninguna rutina con ese ID.", "Error", ERROR_MESSAGE);
                }
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error", ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al borrar rutina: " + ex.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBorrarRutinaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBorrarRutina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarRutina1ActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog(this, "Introduce el nombre del ejercicio a borrar:");

            if (nombre != null && !nombre.trim().isEmpty()) {
                // Buscar si existe
                Ejercicio encontrado = ge.buscarPorNombre(nombre);
                if (encontrado != null) {
                    // Confirmar borrado
                    int confirm = JOptionPane.showConfirmDialog(this, 
                            "¿Estás seguro de borrar el ejercicio \"" + nombre + "\"?",
                            "Confirmar borrado", JOptionPane.YES_NO_OPTION);

                    if (confirm == JOptionPane.YES_OPTION) {
                        ge.borrarPorNombre(nombre);
                        JOptionPane.showMessageDialog(this, "Ejercicio borrado correctamente.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ningún ejercicio con ese nombre.", 
                            "Borrado fallido", JOptionPane.ERROR_MESSAGE);
                }
            } 
            // Si el usuario pulsa "Cancelar", simplemente no hace nada
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al borrar ejercicio: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBorrarRutina1ActionPerformed

    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarRutina;
    private javax.swing.JButton botonBorrarRutina1;
    private javax.swing.JButton botonBorrarUsuarioPorID;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
