/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class ventanaVisualizar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaVisualizar.class.getName());

    /**
     * Creates new form ventanaVisualizar
     */
    public ventanaVisualizar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonRutina = new javax.swing.JButton();
        botonUsuario = new javax.swing.JButton();
        botonVolver1 = new javax.swing.JButton();
        etiTitulo = new javax.swing.JLabel();
        botonEjercicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonRutina.setText("Rutinas");
        botonRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRutinaActionPerformed(evt);
            }
        });

        botonUsuario.setText("Usuarios");
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });

        botonVolver1.setText("Volver");
        botonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolver1ActionPerformed(evt);
            }
        });

        etiTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiTitulo.setText("¿Que desea Visualizar?");

        botonEjercicio.setText("Ejercicios");
        botonEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(etiTitulo)
                .addGap(39, 39, 39)
                .addComponent(botonEjercicio)
                .addGap(18, 18, 18)
                .addComponent(botonRutina)
                .addGap(18, 18, 18)
                .addComponent(botonUsuario)
                .addGap(18, 18, 18)
                .addComponent(botonVolver1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRutinaActionPerformed
        // TODO add your handling code here:
        visualizarRutinas();
    }//GEN-LAST:event_botonRutinaActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        // TODO add your handling code here:
        visualizarUsuarios();
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void botonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolver1ActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolver1ActionPerformed

    private void botonEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjercicioActionPerformed
        // TODO add your handling code here:
        visualizarEjercicios();
    }//GEN-LAST:event_botonEjercicioActionPerformed
   
    public void visualizarEjercicios() {
        JOptionPane.showMessageDialog(this, ge.toString());
    }
    
    public void visualizarRutinas() {
        JOptionPane.showMessageDialog(this, gr.toString());
    }
    
    public void visualizarUsuarios() {
        JOptionPane.showMessageDialog(this, gu.toString());
    }
    
    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEjercicio;
    private javax.swing.JButton botonRutina;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JButton botonVolver1;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
