/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import excepciones.MyException;
import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import modelo.Usuario;

/**
 *
 * @author Alumno
 */
public class ventanaBuscar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaBuscar.class.getName());

    /**
     * Creates new form ventanaBuscar
     */
    public ventanaBuscar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscarNombre = new javax.swing.JButton();
        botonBuscarEdad = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Buscador Usuarios");

        botonBuscarNombre.setText("Buscar por Nombre");
        botonBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarNombreActionPerformed(evt);
            }
        });

        botonBuscarEdad.setText("Buscar por Edad");
        botonBuscarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEdadActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(botonVolver)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarNombreActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = "";
            nombre = JOptionPane.showInputDialog(this, "Introduzca el nombre del usuario que busca:");
            if (nombre != null && !nombre.isEmpty()) {
                Usuario u = gu.buscarPorNombre(nombre);
                if (u != null) {
                    JOptionPane.showMessageDialog(this, u.toString(), "Usuario encontrado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro ningun usuario con ese nombre", "Busqueda fallida", ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error, asegurese de poner bien los datos", "Error", ERROR_MESSAGE);
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar usuario: " + ex.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarNombreActionPerformed

    private void botonBuscarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEdadActionPerformed
        // TODO add your handling code here:
        try {
            String edadStr = JOptionPane.showInputDialog(this, "Introduzca la edad de los usuarios que busca:");
            int edad = Integer.parseInt(edadStr);
            String resultado = gu.mostrarPorEdad(edad);
                if (resultado != null) {
                    JOptionPane.showMessageDialog(this, resultado, "Usuario encontrado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro ningun usuario con esa edad", "Busqueda fallida", ERROR_MESSAGE);
                }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error, asegurese de poner bien los datos", "Error", ERROR_MESSAGE);
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar usuario: " + ex.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarEdadActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarEdad;
    private javax.swing.JButton botonBuscarNombre;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
