/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import gestores.GestorBD;
import gestores.GestorEjercicios;
import gestores.GestorFicheros;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.GimnasioXML;
import modelo.Usuario;

/**
 *
 * @author Alumno
 */
public class ventanaImportar extends javax.swing.JFrame {
    GestorUsuarios gu;
    GestorRutinas gr;
    GestorEjercicios ge;
    GestorFicheros gf;
    GestorBD gbd;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaImportar.class.getName());

    /**
     * Creates new form ventanaImportar
     */
    public ventanaImportar(GestorUsuarios gu, GestorRutinas gr, GestorEjercicios ge, GestorFicheros gf, GestorBD gbd) {
        this.gu = gu;
        this.gr = gr;
        this.ge = ge;
        this.gf = gf;
        this.gbd = gbd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonTexto = new javax.swing.JButton();
        etiImportar = new javax.swing.JLabel();
        botonBinario = new javax.swing.JButton();
        botonDom = new javax.swing.JButton();
        botonSax = new javax.swing.JButton();
        botonJAXB = new javax.swing.JButton();
        botonSQLite = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonTexto.setText("Texto");
        botonTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTextoActionPerformed(evt);
            }
        });

        etiImportar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiImportar.setText("Importar");

        botonBinario.setText("Binario");
        botonBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBinarioActionPerformed(evt);
            }
        });

        botonDom.setText("DOM");
        botonDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDomActionPerformed(evt);
            }
        });

        botonSax.setText("SAX");
        botonSax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaxActionPerformed(evt);
            }
        });

        botonJAXB.setText("JAXB");
        botonJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJAXBActionPerformed(evt);
            }
        });

        botonSQLite.setText("SQLite");
        botonSQLite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSQLiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(etiImportar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(etiImportar)
                .addGap(18, 18, 18)
                .addComponent(botonTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(botonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTextoActionPerformed
        // TODO add your handling code here:
        try {
            GestorFicheros.importarTodoTexto(gu, gr, ge);
            JOptionPane.showMessageDialog(this, 
                "Datos importados correctamente desde los archivos:\n" +
                "usuarios.txt\nrutinas.txt\nejercicios.txt", 
                "Importación completada", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al importar los datos: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonTextoActionPerformed

    private void botonBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBinarioActionPerformed
        // TODO add your handling code here:
        try {
            gu.getUsuarios().clear();
            gu.getUsuarios().addAll(GestorFicheros.importarUsuariosBinario());

            gr.getRutinas().clear();
            gr.getRutinas().addAll(GestorFicheros.importarRutinasBinario());

            ge.getEjercicios().clear();
            ge.getEjercicios().addAll(GestorFicheros.importarEjerciciosBinario());

            JOptionPane.showMessageDialog(this, "Datos importados correctamente en formato binario.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al exportar los datos: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBinarioActionPerformed

    private void botonDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDomActionPerformed
        // TODO add your handling code here:                                                
        // Llamar a la importación DOM completa
        gf.importarTodoXML(gu, gr, ge);
        JOptionPane.showMessageDialog(this, "Datos importados correctamente desde XML (DOM).");
    }//GEN-LAST:event_botonDomActionPerformed

    private void botonSaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaxActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ArrayList<Usuario> usuariosImportados = gf.importarSAX(archivo.getAbsolutePath());

            if (usuariosImportados != null && !usuariosImportados.isEmpty()) {
                gu.getUsuarios().clear();
                gu.getUsuarios().addAll(usuariosImportados);

                JOptionPane.showMessageDialog(this,
                    "Importación con SAX completada. " + usuariosImportados.size() + " usuarios cargados.",
                    "Importar XML (SAX)", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "No se importaron usuarios o el archivo estaba vacío.",
                    "Importar XML (SAX)", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonSaxActionPerformed

    private void botonJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJAXBActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            GimnasioXML datos = gf.importarJAXB(chooser.getSelectedFile().getAbsolutePath());

            if (datos != null) {
                gu.getUsuarios().clear();
                gu.getUsuarios().addAll(datos.getUsuarios());

                gr.getRutinas().clear();
                gr.getRutinas().addAll(datos.getRutinas());

                ge.getEjercicios().clear();
                ge.getEjercicios().addAll(datos.getEjercicios());

                JOptionPane.showMessageDialog(this, "Importación JAXB realizada correctamente");
            }
        }
    }//GEN-LAST:event_botonJAXBActionPerformed

    private void botonSQLiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSQLiteActionPerformed
        // TODO add your handling code here:
        if (gbd == null) {
            gbd = new GestorBD();
        }
        gbd.importarTodo(gu, gr, ge);
    }//GEN-LAST:event_botonSQLiteActionPerformed

    private void volver() {
        this.dispose(); // cierra solo esta ventana
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBinario;
    private javax.swing.JButton botonDom;
    private javax.swing.JButton botonJAXB;
    private javax.swing.JButton botonSQLite;
    private javax.swing.JButton botonSax;
    private javax.swing.JButton botonTexto;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiImportar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
