/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGUI;

import excepciones.MyException;
import gestores.GestorEjercicios;
import gestores.GestorRutinas;
import gestores.GestorUsuarios;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Alumno
 */
public class ventanaInsertarEjercicio extends javax.swing.JFrame {
    GestorRutinas gr;
    GestorUsuarios gu;
    GestorEjercicios ge;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventanaInsertarEjercicio.class.getName());

    /**
     * Creates new form ventanaInsertarEjercicio
     */
    public ventanaInsertarEjercicio(GestorEjercicios ge, GestorRutinas gr) {
        this.ge = ge;
        this.gr = gr;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        etiTitulo1 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        etiNombre = new javax.swing.JLabel();
        etiEdad = new javax.swing.JLabel();
        fieldGrupoMuscular = new javax.swing.JTextField();
        etiPeso = new javax.swing.JLabel();
        fieldDescripcion = new javax.swing.JTextField();
        etiAltura = new javax.swing.JLabel();
        fieldidRutina = new javax.swing.JTextField();
        botonInsertar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiTitulo1.setText("Insertar Ejercicio");

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        etiNombre.setText("nombre ejercicio");

        etiEdad.setText("grupo muscular");

        etiPeso.setText("descripcion");

        etiAltura.setText("Numero de rutina al que pertenece");

        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(etiTitulo1))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiAltura)
                            .addComponent(fieldidRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiPeso)
                            .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiEdad)
                            .addComponent(fieldGrupoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiNombre)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(botonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                    .addContainerGap(211, Short.MAX_VALUE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGrupoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiAltura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldidRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(botonInsertar)
                .addContainerGap())
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(botonVolver)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        try {
            // 1. Comprobar campos no estan vacios y Recoger datos de los campos
            System.out.println("Total rutinas registradas: " + gr.getRutinas().size());
            comprobarCampos();
            String nombre = fieldNombre.getText();
            String grupoMuscular = fieldGrupoMuscular.getText();
            String desc = fieldDescripcion.getText();
            int idRutina = Integer.parseInt(fieldidRutina.getText());
            // 2. Insertar con el gestor
            ge.insertar(nombre, grupoMuscular, desc, idRutina);
            // 3. Mostrar confirmación
            JOptionPane.showMessageDialog(this, "Ejercicio insertado correctamente", "Exito", INFORMATION_MESSAGE);
            // 4. Limpiar campos
            fieldNombre.setText("");
            fieldGrupoMuscular.setText("");
            fieldDescripcion.setText("");
            fieldidRutina.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error, asegurese de poner bien los datos", "Error", ERROR_MESSAGE);
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar ejercicio: " + ex.getMessage(), "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void comprobarCampos() {
        if (fieldNombre.getText().isEmpty() || fieldGrupoMuscular.getText().isEmpty() || fieldDescripcion.getText().isEmpty() || fieldidRutina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", ERROR_MESSAGE);
            return;
        }
    }
    
    private void volver() {
    this.dispose(); // cierra solo esta ventana
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiAltura;
    private javax.swing.JLabel etiEdad;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiPeso;
    private javax.swing.JLabel etiTitulo1;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldGrupoMuscular;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldidRutina;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
